### ISSUE TITLE
Setup works fine, but /blockhunt join causes an internal server error

### ISSUE THREAD

**Issue by LanternServer** [OguzhanUmutlu/BlockHunt#10]
Pretty much the title... please fix we built a huge map for it and it looks really cool!

**Comment by OguzhanUmutlu** [comment]
send the error

**Comment by LanternServer** [comment]
Ok I'll get it rn

**Comment by LanternServer** [comment]
Bruh it works perfectly this time xD

**Comment by LanternServer** [comment]
Thank you for making another awesome game!

**Comment by OguzhanUmutlu** [comment]
> Bruh it works perfectly this time xD

lol

**Comment by OguzhanUmutlu** [comment]
> Thank you for making another awesome game!

you are welcome
