### ISSUE TITLE
Error With join sign

### ISSUE THREAD

**Issue by DRAGKILLS** [OguzhanUmutlu/BlockHunt#18]

**Comment by DRAGKILLS** [comment]
Create arena add join sign if done u will get the error

**Comment by OguzhanUmutlu** [comment]
whats the error

**Comment by DRAGKILLS** [comment]
Vector3::$level is undefined

**Comment by DRAGKILLS** [comment]
And index joinSign is undefined

**Comment by OguzhanUmutlu** [comment]
lemme check it

**Comment by DRAGKILLS** [comment]
ok

**Comment by llPushkarSinghll** [comment]
Hi xd

**Comment by OguzhanUmutlu** [comment]
hi

**Comment by llPushkarSinghll** [comment]
> hi

Hi

**Comment by OguzhanUmutlu** [comment]
> > hi
> 
> Hi

HI

**Comment by OguzhanUmutlu** [comment]
> And index joinSign is undefined

fixed it ;)
can you please try it

**Comment by llPushkarSinghll** [comment]
> > > hi
> > 
> > 
> > Hi
> 
> HI

Hi

**Comment by DRAGKILLS** [comment]
hi

**Comment by DRAGKILLS** [comment]
> > And index joinSign is undefined
> 
> fixed it ;)
> can you please try it

Ok

**Comment by llPushkarSinghll** [comment]
> hi

Hi , u still remember or u forgot?

**Comment by OguzhanUmutlu** [comment]
> > hi
> 
> Hi , u still remember or u forgot?

hi!?

**Comment by llPushkarSinghll** [comment]
> > > hi
> > 
> > 
> > Hi , u still remember or u forgot?
> 
> hi!?

Hi

**Comment by OguzhanUmutlu** [comment]
> > > > hi
> > > 
> > > 
> > > Hi , u still remember or u forgot?
> > 
> > 
> > hi!?
> 
> Hi

omg stop

**Comment by llPushkarSinghll** [comment]
> > > > > hi
> > > > 
> > > > 
> > > > Hi , u still remember or u forgot?
> > > 
> > > 
> > > hi!?
> > 
> > 
> > Hi
> 
> omg stop and hi

Ok and hi

**Comment by OguzhanUmutlu** [comment]
> > > > > > hi
> > > > > 
> > > > > 
> > > > > Hi , u still remember or u forgot?
> > > > 
> > > > 
> > > > hi!?
> > > 
> > > 
> > > Hi
> > 
> > 
> > omg stop and hi
> 
> Ok and hi

hi!!

**Comment by llPushkarSinghll** [comment]
> > > > > > > hi
> > > > > > 
> > > > > > 
> > > > > > Hi , u still remember or u forgot?
> > > > > 
> > > > > 
> > > > > hi!?
> > > > 
> > > > 
> > > > Hi
> > > 
> > > 
> > > omg stop and hi
> > 
> > 
> > Ok and hi
> 
> hi!!
@DRAGKILLS  accept friend request in discord ._. and hi

**Comment by DRAGKILLS** [comment]
undefined property: Arena::$players

**Comment by OguzhanUmutlu** [comment]
hm

**Comment by OguzhanUmutlu** [comment]
> undefined property: Arena::$players

where

**Comment by DRAGKILLS** [comment]
Arena at line 334

**Comment by DRAGKILLS** [comment]
And change from TntTag lol

**Comment by OguzhanUmutlu** [comment]
> And change from TntTag lol

ah s*it here we go again

**Comment by OguzhanUmutlu** [comment]
also fixed it

**Comment by DRAGKILLS** [comment]
Ok

**Comment by DRAGKILLS** [comment]
Change line 334 $this->players

**Comment by OguzhanUmutlu** [comment]
i fixed it already

**Comment by OguzhanUmutlu** [comment]
wait it didnt save

**Comment by OguzhanUmutlu** [comment]
fixed it

**Comment by DRAGKILLS** [comment]
done now close

**Comment by DRAGKILLS** [comment]
but if i click in the sign i dont join the arena

**Comment by OguzhanUmutlu** [comment]
hmm i didnt add it

**Comment by DRAGKILLS** [comment]
add it if u add it close this

**Comment by OguzhanUmutlu** [comment]
ok bye ty

**Comment by DRAGKILLS** [comment]
but first change from TntTag loll

**Comment by OguzhanUmutlu** [comment]
lol

**Comment by OguzhanUmutlu** [comment]
im busy rn but i will
*i hope*
