### ISSUE TITLE
Error plugin

### ISSUE THREAD

**Issue by kostamax27** [OguzhanUmutlu/BlockHunt#4]
![Screenshot_2021-07-22-09-52-56-388_io scer pocketmine](https://user-images.githubusercontent.com/69608272/126600190-41215c21-4b23-4531-862e-f1c7a13817ce.jpg)

![Screenshot_2021-07-22-09-52-47-757_io scer pocketmine](https://user-images.githubusercontent.com/69608272/126600201-f3cd9a2b-cfcb-4f0e-98e7-b7371a5fcae6.jpg)

**Comment by OguzhanUmutlu** [comment]
fixed use last phar
