### ISSUE TITLE
Plugin error

### ISSUE THREAD

**Issue by kostamax27** [OguzhanUmutlu/BlockHunt#5]
![Screenshot_2021-07-22-12-40-47-688_io scer pocketmine](https://user-images.githubusercontent.com/69608272/126619483-16541608-40c2-4659-8bf3-919f4cb32886.jpg)

![Screenshot_2021-07-22-12-40-38-071_io scer pocketmine](https://user-images.githubusercontent.com/69608272/126619500-ed146dda-c218-4887-ac19-a1e8bb17d838.jpg)

**Comment by OguzhanUmutlu** [comment]
fixed use last phar
