### ISSUE TITLE
Suggestion - Different Inventory

### ISSUE THREAD

**Issue by xKurt** [OguzhanUmutlu/BlockHunt#7]
Hello,

Just a suggestion if it's possible for the players to have their own (different) inventory? For eg. they have their own items at the lobby and once they joined blockhunt they'll have new inventory, they'll have the items back again (the items from the lobby) after the game.

I think it'll be helpful

**Comment by OguzhanUmutlu** [comment]
hmm yes its a good idea
but i dont know if poggit allows these core things for plugins
