### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by MrBlasyMSK** [OguzhanUmutlu/BlockHunt#8]
![image](https://user-images.githubusercontent.com/85447029/126791614-8e47f06c-d944-4dae-b973-e5d0b0fa1c9c.png)
I also included that you go through blocks down when you transform into a solid block.

**Comment by OguzhanUmutlu** [comment]
?

**Comment by MrBlasyMSK** [comment]
If you die the respawn buttons do not appear, and then if you become a block on top of a slab block then you fall down (if there is no block below that slab block)

**Comment by ZandercraftGames** [comment]
> If you die the respawn buttons do not appear, and then if you become a block on top of a slab block then you fall down (if there is no block below that slab block)

This is a Pocketmine issue iirc.

**Comment by DRAGKILLS** [comment]
u can fix it with 
$p?->spawnToAll();
$p?->respawnToAll(); [ik its closed]
